### PR TITLE
Migrate from CRA to Vite

### PR DESCRIPTION
**Pull request by neorth**
While looking into a crash I had trouble getting a good stack trace and the source maps didn't point to the correct location. So I thought, wth, lets migrate this to Vite. 

Right now this is just a draft. A few things needs to be fixed:

- [ ] Decide if this migration is wanted
- [ ] Fix tests
- [ ] Update readme
- [ ] What else I forgot

### CODE REVIEW

**Comment by perliedman** [comment]
Hi Joakim! :wave: :slightly_smiling_face: 

I have contemplated switching to Vite a few times but decided to put it further down on my todo. If you're interested in fixing the outstanding issues you mention above, I'd be :+1: for this change!

**Comment by neorth** [comment]
Great! I took a quick look at the tests and it looks like there will be som work getting jest to run when using vite, maybe it would be better to migrate to vitest while we're at it?

I don't really have an abundance of free time but I hope to get to it some evening ahead :)

**Comment by perliedman** [comment]
My github notifications is a mess, so saw this only now, sorry. But go for it! Haven't used vitest, but from the name it sounds like it makes sense if we're migrating to vite!

**Comment by perliedman** [comment]
Fixed by #22!

**Pull request closed without merging**
